import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { ACTIVE_GG_IMPORT_BATCH_KEY, clearActiveGgImportBatch, hasRemainingImportCandidates, isActiveGgImportBatch, markImportCandidatesSurfaced, nextImportCandidates, parseActiveGgImportBatch, readActiveGgImportBatch, remainingImportCandidates, surfaceNextImportCandidates, writeActiveGgImportBatch, type ActiveGgImportBatch } from "../lib/activeGgImportBatch";
import { MAX_IMPORT_CANDIDATES, selectHandReviewCandidatePool, selectHandReviewSuggestions } from "../lib/handSuggestions";
import { GG_IMPORTS_KEY, HAND_SUGGESTIONS_KEY, MAX_PENDING_HAND_SUGGESTIONS } from "../lib/handSuggestionStorage";
import type { HandReviewSuggestion, HandReviewSuggestionReason, ParsedGgHand } from "../lib/types";

const now = "2026-08-23T12:00:00.000Z";
const parsed = (id: string, kind: HandReviewSuggestionReason, order = 0): ParsedGgHand => ({
  sourceHandId: id, playedAt: `2026-08-23T${String(order).padStart(2, "0")}:00:00.000Z`, game: "holdem-no-limit", smallBlind: .01, bigBlind: .02,
  heroCards: ["Ah", "Kh"], actions: [], heroDecisionCount: order + 1, heroAllIn: kind === "high-commitment", heroShows: kind === "hero-showdown",
  heroDecisionStreets: kind === "river-decision" ? ["river"] : kind === "long-line" ? ["flop", "turn", "river"] : ["preflop"],
  heroFacedAggressionStreets: kind === "multi-street-pressure" ? ["preflop", "flop"] : [], rawHandText: `Poker Hand #${id}`,
});
const candidate = (id: string, reason: HandReviewSuggestionReason = "long-line"): HandReviewSuggestion => ({ id: `${reason}:${id}`, source: "gg-pokercraft", sourceHandId: id, reason, createdAt: now, heroCards: ["Ah", "Kh"], playedAt: now, reasonLabel: "LINHA", reasonMessage: "Estrutura observável.", rawHandText: `Poker Hand #${id}` });
const batch = (candidates = [candidate("1"), candidate("2"), candidate("3")], surfacedSuggestionIds: string[] = []): ActiveGgImportBatch => ({ version: 1, fingerprint: "a".repeat(64), importedAt: now, recognizedHands: 437, ignoredHands: 2, candidates, surfacedSuggestionIds });
function storage(values = new Map<string, string>(), fail = false) { Object.defineProperty(globalThis, "window", { configurable: true, value: { localStorage: { getItem: (key: string) => values.get(key) ?? null, removeItem: (key: string) => values.delete(key), setItem: (key: string, value: string) => { if (fail) throw new Error("quota"); values.set(key, value); } } } }); return values; }
function cleanup() { delete (globalThis as { window?: unknown }).window; }

test("os primeiros cinco do pool preservam exatamente a triagem V0.16", () => { const hands = (["high-commitment", "river-decision", "hero-showdown", "multi-street-pressure", "long-line"] as const).flatMap((reason) => [parsed(`${reason}-1`, reason, 1), parsed(`${reason}-2`, reason, 2)]); assert.deepEqual(selectHandReviewCandidatePool(hands, { createdAt: now }).slice(0, 5), selectHandReviewSuggestions(hands, { createdAt: now })); });
test("pool progride por rodadas na ordem fixa e inclui mais de cinco", () => { const reasons = ["high-commitment", "river-decision", "hero-showdown", "multi-street-pressure", "long-line"] as const; const rank: Record<HandReviewSuggestionReason, number> = { "high-commitment": 8, "river-decision": 20, "hero-showdown": 6, "multi-street-pressure": 4, "long-line": 0 }; const pool = selectHandReviewCandidatePool(reasons.flatMap((reason) => [parsed(`${reason}-a`, reason, rank[reason]), parsed(`${reason}-b`, reason, rank[reason] + 1)]), { createdAt: now }); assert.ok(pool.length > 5); assert.deepEqual(pool.slice(0, 5).map((x) => x.reason), reasons); assert.deepEqual(pool.slice(5, 9).map((x) => x.reason), reasons.slice(0, 4)); assert.equal(pool[9].reason, "river-decision"); });
test("categoria esgotada não bloqueia categorias nas rodadas seguintes", () => { const pool = selectHandReviewCandidatePool([parsed("show-only", "hero-showdown"), parsed("river-1", "river-decision"), parsed("river-2", "river-decision")], { createdAt: now }); assert.ok(pool.some(({ sourceHandId }) => sourceHandId === "river-2")); });
test("pool respeita teto operacional e unicidade global", () => { const hands = Array.from({ length: 80 }, (_, index) => parsed(String(index), "long-line", index % 24)); const pool = selectHandReviewCandidatePool([...hands, hands[0]], { createdAt: now }); assert.equal(pool.length, MAX_IMPORT_CANDIDATES); assert.equal(new Set(pool.map((x) => x.sourceHandId)).size, pool.length); assert.equal(new Set(pool.map((x) => x.id)).size, pool.length); });
test("resultado textual não participa da seleção", () => { const a = parsed("a", "river-decision"); const b = parsed("b", "river-decision"); a.rawHandText += "\nHero collected $9"; b.rawHandText += "\nVillain collected $9"; const before = selectHandReviewCandidatePool([a, b], { createdAt: now }).map((x) => x.sourceHandId); a.rawHandText = a.rawHandText.replace("Hero", "Villain"); b.rawHandText = b.rawHandText.replace("Villain", "Hero"); assert.deepEqual(selectHandReviewCandidatePool([a, b], { createdAt: now }).map((x) => x.sourceHandId), before); });

test("batch válido exige fingerprint SHA-256 e timestamps válidos", () => { assert.equal(isActiveGgImportBatch(batch()), true); assert.equal(isActiveGgImportBatch({ ...batch(), fingerprint: "bad" }), false); assert.equal(isActiveGgImportBatch({ ...batch(), importedAt: "bad" }), false); });
test("batch rejeita id vazio e candidate inválida", () => { assert.equal(isActiveGgImportBatch(batch([{ ...candidate("1"), id: "" }])), false); assert.equal(isActiveGgImportBatch(batch([{ ...candidate("1"), rawHandText: "" }])), false); });
test("batch rejeita sourceHandId e suggestion id duplicados", () => { assert.equal(isActiveGgImportBatch(batch([candidate("1"), { ...candidate("2"), sourceHandId: "1" }])), false); assert.equal(isActiveGgImportBatch(batch([candidate("1"), { ...candidate("2"), id: candidate("1").id }])), false); });
test("batch rejeita surfaced inexistente ou duplicado", () => { assert.equal(isActiveGgImportBatch(batch(undefined, ["missing"])), false); const one = candidate("1").id; assert.equal(isActiveGgImportBatch(batch(undefined, [one, one])), false); });
test("parser e leitura tratam ausência e JSON corrompido como lote inexistente", () => { assert.equal(parseActiveGgImportBatch(null), null); assert.equal(parseActiveGgImportBatch("{"), null); storage(); assert.equal(readActiveGgImportBatch(), null); cleanup(); });
test("write/read preserva a posição do lote após reload", () => { storage(); const current = batch(undefined, [candidate("1").id]); writeActiveGgImportBatch(current); assert.deepEqual(readActiveGgImportBatch(), current); cleanup(); });

test("+5 e +10 adicionam no máximo o pedido", () => { const current = batch(Array.from({ length: 20 }, (_, i) => candidate(String(i)))); assert.equal(surfaceNextImportCandidates(current, 5, []).added.length, 5); assert.equal(surfaceNextImportCandidates(current, 10, []).added.length, 10); });
test("pending nunca passa de quinze e pedido parcial usa somente o espaço", () => { const current = batch(Array.from({ length: 30 }, (_, i) => candidate(String(i)))); const pending = current.candidates.slice(0, 12); const marked = markImportCandidatesSurfaced(current, pending); const result = surfaceNextImportCandidates(marked, 10, pending); assert.equal(result.added.length, 3); assert.equal(result.suggestions.length, MAX_PENDING_HAND_SUGGESTIONS); });
test("pool quase esgotado devolve somente restantes", () => { const current = batch(); const marked = markImportCandidatesSurfaced(current, current.candidates.slice(0, 2)); assert.equal(nextImportCandidates(marked, 10).length, 1); });
test("mão surfaced nunca retorna depois de salvar ou descartar pending", () => { const current = batch(); const consumed = markImportCandidatesSurfaced(current, [current.candidates[0]]); assert.deepEqual(nextImportCandidates(consumed, 10, []).map((x) => x.id), current.candidates.slice(1).map((x) => x.id)); });
test("lote esgotado não retorna sugestões e informa estado", () => { const current = batch(); const exhausted = markImportCandidatesSurfaced(current, current.candidates); assert.equal(hasRemainingImportCandidates(exhausted), false); assert.deepEqual(remainingImportCandidates(exhausted), []); assert.deepEqual(nextImportCandidates(exhausted, 10), []); });
test("marcar surfaced é idempotente e não duplica ids", () => { const current = batch(); const marked = markImportCandidatesSurfaced(markImportCandidatesSurfaced(current, [current.candidates[0]]), [current.candidates[0]]); assert.deepEqual(marked.surfacedSuggestionIds, [current.candidates[0].id]); });
test("encerrar lote limpa somente batch, preservando mãos, snapshots e fingerprint", () => { const values = storage(new Map([[ACTIVE_GG_IMPORT_BATCH_KEY, JSON.stringify(batch())], ["poker-loop-v1:real-hands", "hands"], ["poker-loop-v1:real-hand-reasoning-snapshots", "snapshots"], [GG_IMPORTS_KEY, "fingerprints"], [HAND_SUGGESTIONS_KEY, "pending"]])); clearActiveGgImportBatch(); assert.equal(values.has(ACTIVE_GG_IMPORT_BATCH_KEY), false); assert.equal(values.get("poker-loop-v1:real-hands"), "hands"); assert.equal(values.get("poker-loop-v1:real-hand-reasoning-snapshots"), "snapshots"); assert.equal(values.get(GG_IMPORTS_KEY), "fingerprints"); assert.equal(values.get(HAND_SUGGESTIONS_KEY), "pending"); cleanup(); });
test("falha de storage não apaga dados existentes", () => { const values = storage(new Map([[HAND_SUGGESTIONS_KEY, "existing"], ["poker-loop-v1:real-hands", "hands"]]), true); assert.throws(() => writeActiveGgImportBatch(batch())); assert.equal(values.get(HAND_SUGGESTIONS_KEY), "existing"); assert.equal(values.get("poker-loop-v1:real-hands"), "hands"); cleanup(); });
test("módulo não importa motor pedagógico, diagnóstico ou learning loop", () => { const source = readFileSync("lib/activeGgImportBatch.ts", "utf8"); for (const forbidden of ["trainingEngine", "diagnostics", "learningLoop", "won", "lost", "profit", "potWon", "netResult"]) assert.equal(source.includes(forbidden), false); });
