import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { ACTIVE_GG_IMPORT_BATCH_KEY, nextImportCandidates, persistGgImportTransition, type ActiveGgImportBatch } from "../lib/activeGgImportBatch";
import { countRemainingCandidatesByFilter, deriveCandidateStructuralTags, GG_EXPLORATION_FILTERS, nextImportCandidatesForFilter, surfaceImportCandidatesForFilter } from "../lib/ggImportExploration";
import { HAND_SUGGESTIONS_KEY, MAX_PENDING_HAND_SUGGESTIONS } from "../lib/handSuggestionStorage";
import type { HandReviewSuggestion, HandReviewSuggestionReason } from "../lib/types";

const now = "2026-08-23T12:00:00.000Z";
function raw(id: string, options: { river?: boolean; riverAggression?: boolean; shows?: boolean; allIn?: boolean; turnPressure?: boolean; contribution?: number; winner?: "Hero" | "Villain" } = {}) {
  const river = options.river || options.riverAggression;
  return [`Poker Hand #${id}: Hold'em No Limit ($1/$2) - 2026/08/23 12:00:00`, "Table 'Alpha' 6-max Seat #1 is the button", "Seat 1: Hero ($100 in chips)", "Seat 2: Villain ($100 in chips)", "Dealt to Hero [Ah Kh]", "Hero: calls $2", "*** FLOP *** [As 7d 2c]", "Villain: bets $5", "Hero: calls $5", "*** TURN *** [As 7d 2c] [9h]", ...(options.turnPressure ? ["Villain: bets $8"] : []), "Hero: checks", ...(river ? ["*** RIVER *** [As 7d 2c 9h] [3s]", ...(options.riverAggression ? ["Villain: bets $10"] : []), `Hero: ${options.allIn ? "raises $20 to $90 and is all-in" : `calls $${options.contribution ?? 10}`}`] : []), "*** SHOW DOWN ***", ...(options.shows ? ["Hero: shows [Ah Kh]"] : []), `${options.winner ?? "Hero"} collected $200 from pot`].join("\n");
}
function candidate(id: string, options = {}, reason: HandReviewSuggestionReason = "high-commitment"): HandReviewSuggestion { return { id: `${reason}:${id}`, source: "gg-pokercraft", sourceHandId: id, reason, createdAt: now, heroCards: ["Ah", "Kh"], playedAt: now, reasonLabel: "ESTRUTURA", reasonMessage: "Característica observável.", rawHandText: raw(id, options) }; }
function batch(candidates: HandReviewSuggestion[], surfacedSuggestionIds: string[] = []): ActiveGgImportBatch { return { version: 1, fingerprint: "a".repeat(64), importedAt: now, recognizedHands: candidates.length, ignoredHands: 0, candidates, surfacedSuggestionIds }; }
function failingStorage(values: Map<string, string>) { let writes = 0; Object.defineProperty(globalThis, "window", { configurable: true, value: { localStorage: { getItem: (key: string) => values.get(key) ?? null, removeItem: (key: string) => values.delete(key), setItem: (key: string, value: string) => { writes++; if (writes === 2) throw new Error("write 2"); values.set(key, value); } } } }); }
const cleanup = () => delete (globalThis as { window?: unknown }).window;

test("river-decision exige uma decisão do Herói no river", () => { assert.ok(deriveCandidateStructuralTags(candidate("river", { river: true })).includes("river-decision")); assert.ok(!deriveCandidateStructuralTags(candidate("turn")).includes("river-decision")); });
test("river-facing-aggression exige agressão enfrentada especificamente no river", () => { assert.ok(deriveCandidateStructuralTags(candidate("river-agg", { riverAggression: true })).includes("river-facing-aggression")); assert.ok(!deriveCandidateStructuralTags(candidate("flop-only", { river: true })).includes("river-facing-aggression")); });
test("hero-showdown usa Hero shows, não apenas a seção SHOW DOWN", () => { assert.ok(deriveCandidateStructuralTags(candidate("shows", { shows: true })).includes("hero-showdown")); assert.ok(!deriveCandidateStructuralTags(candidate("section-only")).includes("hero-showdown")); });
test("high-commitment mantém all-in ou ratio de pelo menos 0.25 com decisão", () => { assert.ok(deriveCandidateStructuralTags(candidate("allin", { river: true, allIn: true })).includes("high-commitment")); assert.ok(deriveCandidateStructuralTags(candidate("boundary", { river: true, contribution: 18 })).includes("high-commitment")); assert.ok(!deriveCandidateStructuralTags(candidate("below", { river: true, contribution: 17 })).includes("high-commitment")); });
test("multi-street-pressure mantém agressão enfrentada em duas streets", () => { assert.ok(deriveCandidateStructuralTags(candidate("pressure", { turnPressure: true })).includes("multi-street-pressure")); });
test("long-line mantém decisões no flop, turn e river", () => { assert.ok(deriveCandidateStructuralTags(candidate("long", { river: true })).includes("long-line")); assert.ok(!deriveCandidateStructuralTags(candidate("short")).includes("long-line")); });
test("uma mão recebe múltiplas tags independentemente de suggestion.reason", () => { const item = candidate("multi", { riverAggression: true, shows: true, allIn: true, turnPressure: true }, "high-commitment"); const tags = deriveCandidateStructuralTags(item); assert.deepEqual(tags, GG_EXPLORATION_FILTERS); assert.ok(tags.includes("river-decision")); });
test("raw inválida retorna zero tags sem alterar candidate", () => { const item = { ...candidate("bad"), rawHandText: "inválida" }; const before = structuredClone(item); assert.deepEqual(deriveCandidateStructuralTags(item), []); assert.deepEqual(item, before); });
test("resultado financeiro e vencedor não participam das tags", () => { const hero = candidate("same", { riverAggression: true, shows: true, winner: "Hero" }); const villain = { ...hero, rawHandText: raw("same", { riverAggression: true, shows: true, winner: "Villain" }) }; assert.deepEqual(deriveCandidateStructuralTags(hero), deriveCandidateStructuralTags(villain)); });
test("contagens incluem somente não surfaced e permitem sobreposição", () => { const a = candidate("a", { riverAggression: true, shows: true }); const b = candidate("b", { river: true }); const current = batch([a, b]); const counts = countRemainingCandidatesByFilter(current); assert.equal(counts["river-decision"], 2); assert.equal(counts["hero-showdown"], 1); assert.ok(Object.values(counts).reduce((sum, count) => sum + count, 0) > current.candidates.length); assert.equal(countRemainingCandidatesByFilter(batch([a, b], [a.id]))["hero-showdown"], 0); });
test("seleção filtrada mantém a ordem original do pool", () => { const items = [candidate("1"), candidate("2", { river: true }), candidate("3"), candidate("4", { river: true })]; assert.deepEqual(nextImportCandidatesForFilter(batch(items), "river-decision", 5, []).map(({ sourceHandId }) => sourceHandId), ["2", "4"]); });
test("seleção filtrada ignora surfaced e sourceHandId já pending", () => { const items = [candidate("1", { river: true }), candidate("2", { river: true }), candidate("3", { river: true })]; assert.deepEqual(nextImportCandidatesForFilter(batch(items, [items[0].id]), "river-decision", 5, [{ ...items[1], id: "pending:other" }]).map(({ sourceHandId }) => sourceHandId), ["3"]); });
test("seleção filtrada respeita pedido, filtro vazio e teto de quinze", () => { const items = Array.from({ length: 20 }, (_, index) => candidate(String(index), { river: true })); assert.equal(nextImportCandidatesForFilter(batch(items), "river-decision", 5, []).length, 5); assert.deepEqual(nextImportCandidatesForFilter(batch(items), "hero-showdown", 5, []), []); assert.equal(nextImportCandidatesForFilter(batch(items), "river-decision", 5, Array.from({ length: 13 }, (_, i) => ({ ...candidate(`p${i}`), sourceHandId: `p${i}` }))).length, 2); assert.equal(MAX_PENDING_HAND_SUGGESTIONS, 15); });
test("consumo pelo filtro também remove a mão do +5 geral e vice-versa", () => { const items = [candidate("1", { river: true }), candidate("2", { river: true })]; const filtered = surfaceImportCandidatesForFilter(batch(items), "river-decision", 1, []); assert.deepEqual(nextImportCandidates(filtered.batch, 5, []).map(({ sourceHandId }) => sourceHandId), ["2"]); const generallySurfaced = { ...batch(items), surfacedSuggestionIds: [items[0].id] }; assert.deepEqual(nextImportCandidatesForFilter(generallySurfaced, "river-decision", 5, []).map(({ sourceHandId }) => sourceHandId), ["2"]); });
test("helper filtrado não altera batch nem candidates diretamente", () => { const item = candidate("1", { river: true }); const current = batch([item]); const before = structuredClone(current); surfaceImportCandidatesForFilter(current, "river-decision", 5, []); assert.deepEqual(current, before); assert.deepEqual(item, before.candidates[0]); });
test("transação filtrada faz rollback no segundo write e mantém disponibilidade", () => { const item = candidate("1", { river: true }); const previous = batch([item]); const next = surfaceImportCandidatesForFilter(previous, "river-decision", 5, []); const previousRaw = JSON.stringify(previous); const values = new Map([[ACTIVE_GG_IMPORT_BATCH_KEY, previousRaw], [HAND_SUGGESTIONS_KEY, "[]"]]); failingStorage(values); assert.throws(() => persistGgImportTransition(previous, [], next.batch, next.suggestions)); assert.equal(values.get(ACTIVE_GG_IMPORT_BATCH_KEY), previousRaw); assert.equal(countRemainingCandidatesByFilter(JSON.parse(values.get(ACTIVE_GG_IMPORT_BATCH_KEY)!))["river-decision"], 1); cleanup(); });
test("caminho normal produz pending e surfaced coerentes para reload", () => { const item = candidate("1", { river: true }); const next = surfaceImportCandidatesForFilter(batch([item]), "river-decision", 5, []); assert.deepEqual(next.suggestions, [item]); assert.deepEqual(next.batch.surfacedSuggestionIds, [item.id]); assert.equal(countRemainingCandidatesByFilter(structuredClone(next.batch))["river-decision"], 0); });
test("UI mantém filtro em estado React local e usa a transação V0.30", () => { const source = readFileSync("app/hands/page.tsx", "utf8"); assert.match(source, /useState<GgExplorationFilter>/); assert.match(source, /persistGgImportTransition\(activeImportBatch, suggestions, next\.batch, next\.suggestions\)/); assert.ok(!source.includes("writeSelectedImportFilter")); });
test("exploração não cria storage, classificação estratégica ou dependência pedagógica", () => { const source = readFileSync("lib/ggImportExploration.ts", "utf8"); for (const forbidden of ["localStorage", "trainingEngine", "diagnostics", "learningLoop", "bluff", "thin value", "winner", "loser", "profit", "loss", "net result", "Skill"]) assert.equal(source.includes(forbidden), false); });
