import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { createTrainingSession } from "../lib/activeTrainingSession";
import { investigationTrainingLink } from "../lib/investigationTrainingBridge";
import { INVESTIGATION_TRAINING_LAUNCHES_KEY, findInvestigationTrainingLaunchBySessionId, isInvestigationTrainingLaunch, launchForNewTrainingSession, listInvestigationTrainingLaunchesByEpisodeId, parseInvestigationTrainingLaunches, readInvestigationTrainingLaunches, registerInvestigationTrainingLaunch } from "../lib/investigationTrainingLaunches";
import { createRealHandInvestigationEpisode, REAL_HAND_INVESTIGATION_HISTORY_KEY, type StoredRealHandInvestigationEpisode } from "../lib/realHandInvestigationHistory";
import { clearPrototypeProgress } from "../lib/storage";
import type { ActiveRealHandInvestigation } from "../lib/prospectiveRealHandInvestigation";
import type { Skill } from "../lib/types";

const startedAt = "2026-08-22T12:00:00.000Z";
function episode(id = "episode-1"): StoredRealHandInvestigationEpisode {
  const active: ActiveRealHandInvestigation = { version: 1, id, factor: "size", startedAt: "2026-08-20T00:00:00Z", baselineSnapshotIds: ["a", "b", "c"], baselineHandReviewIds: ["ha", "hb", "hc"], baselineReviewCount: 3, baselineLowOrUnclearCount: 2, prospectiveReviews: Array.from({ length: 5 }, (_, i) => ({ snapshotId: `s${i}`, handReviewId: `h${i}`, createdAt: `2026-08-21T00:00:0${i}Z`, factorPresent: true, selfRatedSupport: "low" })) };
  return createRealHandInvestigationEpisode(active, "completed", "2026-08-21T01:00:00Z");
}
function session(id = "session-1", skill: Skill = "sizing") { return createTrainingSession([], skill, id, startedAt).active; }
function install(initial = new Map<string, string>()) {
  const old = Object.getOwnPropertyDescriptor(globalThis, "window");
  const localStorage = { getItem: (key: string) => initial.get(key) ?? null, setItem: (key: string, value: string) => { initial.set(key, value); }, removeItem: (key: string) => { initial.delete(key); } };
  Object.defineProperty(globalThis, "window", { configurable: true, value: { localStorage } });
  return { values: initial, cleanup: () => old ? Object.defineProperty(globalThis, "window", old) : Reflect.deleteProperty(globalThis, "window") };
}

test("storage vazio e JSON inválido produzem lista vazia", () => { assert.deepEqual(parseInvestigationTrainingLaunches(null), []); assert.deepEqual(parseInvestigationTrainingLaunches("{"), []); });
test("parser ignora item inválido sem eliminar o válido", () => { const valid = { version: 1, episodeId: "e", sessionId: "s", skill: "sizing", launchedAt: startedAt }; assert.deepEqual(parseInvestigationTrainingLaunches(JSON.stringify([{ ...valid, skill: "invalid" }, valid])), [valid]); });
test("validação rejeita Skill, timestamp, versão e identidades inválidos", () => { const valid = { version: 1, episodeId: "e", sessionId: "s", skill: "sizing", launchedAt: startedAt }; assert.equal(isInvestigationTrainingLaunch(valid), true); for (const patch of [{ skill: "bad" }, { launchedAt: "bad" }, { version: 2 }, { episodeId: " " }, { sessionId: "" }]) assert.equal(isInvestigationTrainingLaunch({ ...valid, ...patch }), false); });
test("episódio completed e sessão nova usam identidade, foco e tempo reais", () => { const active = session(); assert.deepEqual(launchForNewTrainingSession("episode-1", active, [episode()]), { version: 1, episodeId: "episode-1", sessionId: active.sessionId, skill: active.focus, launchedAt: active.startedAt }); });
test("origem exige ID exato, completed e focus válido", () => { const completed = episode(); assert.equal(launchForNewTrainingSession("missing", session(), [completed]), null); for (const completion of ["stopped", "inconclusive"] as const) assert.equal(launchForNewTrainingSession(completed.id, session(), [{ ...completed, completion }]), null); assert.equal(launchForNewTrainingSession(completed.id, createTrainingSession([], undefined, "s", startedAt).active, [completed]), null); });
test("registro é idempotente e conflito por episódio ou Skill preserva a origem", () => { const env = install(); const launch = launchForNewTrainingSession("episode-1", session(), [episode()])!; assert.equal(registerInvestigationTrainingLaunch(launch), "created"); assert.equal(registerInvestigationTrainingLaunch(launch), "idempotent"); assert.equal(registerInvestigationTrainingLaunch({ ...launch, episodeId: "other" }), "conflict"); assert.equal(registerInvestigationTrainingLaunch({ ...launch, skill: "range-reading" }), "conflict"); assert.deepEqual(readInvestigationTrainingLaunches(), [launch]); env.cleanup(); });
test("episódios diferentes e várias sessões do mesmo episódio coexistem", () => { const env = install(); const a = launchForNewTrainingSession("episode-1", session("s1"), [episode()])!; const b = launchForNewTrainingSession("episode-1", session("s2"), [episode()])!; const c = launchForNewTrainingSession("episode-2", session("s3"), [episode("episode-2")])!; [a, b, c].forEach(registerInvestigationTrainingLaunch); assert.equal(listInvestigationTrainingLaunchesByEpisodeId(readInvestigationTrainingLaunches(), "episode-1").length, 2); assert.equal(findInvestigationTrainingLaunchBySessionId(readInvestigationTrainingLaunches(), "s3")?.episodeId, "episode-2"); env.cleanup(); });
test("reload encontra a origem por sessionId sem duplicar", () => { const env = install(); const launch = launchForNewTrainingSession("episode-1", session(), [episode()])!; registerInvestigationTrainingLaunch(launch); assert.deepEqual(findInvestigationTrainingLaunchBySessionId(readInvestigationTrainingLaunches(), "session-1"), launch); assert.equal(registerInvestigationTrainingLaunch(launch), "idempotent"); assert.equal(readInvestigationTrainingLaunches().length, 1); env.cleanup(); });
test("reset pedagógico preserva launches", () => { const env = install(new Map([[INVESTIGATION_TRAINING_LAUNCHES_KEY, "launches"], ["poker-loop-v1:attempts", "[]"]])); clearPrototypeProgress(); assert.equal(env.values.get(INVESTIGATION_TRAINING_LAUNCHES_KEY), "launches"); env.cleanup(); });
test("ponte transporta foco escolhido e episodeId exato", () => assert.equal(investigationTrainingLink("episode / exact", "sizing"), "/session?focus=sizing&investigation=episode%20%2F%20exact"));
test("launch contém somente proveniência de início", () => { const launch = launchForNewTrainingSession("episode-1", session(), [episode()])!; assert.deepEqual(Object.keys(launch).sort(), ["episodeId", "launchedAt", "sessionId", "skill", "version"]); assert.doesNotMatch(JSON.stringify(launch), /completed|correct|error|factor|efficacy/); });
test("implementação não mapeia ReasoningFactor nem importa o motor pedagógico", () => { const source = readFileSync("lib/investigationTrainingLaunches.ts", "utf8"); assert.doesNotMatch(source, /ReasoningFactor|factorCount|lowOrUnclearCount|trainingEngine|diagnostics|learningLoop/); });
test("criar launch não modifica sessão nem episódio", () => { const active = session(); const historical = episode(); const beforeSession = JSON.stringify(active); const beforeEpisode = JSON.stringify(historical); launchForNewTrainingSession(historical.id, active, [historical]); assert.equal(JSON.stringify(active), beforeSession); assert.equal(JSON.stringify(historical), beforeEpisode); });
test("storage separado pode ser lido com histórico presente", () => { const launch = launchForNewTrainingSession("episode-1", session(), [episode()])!; const env = install(new Map([[REAL_HAND_INVESTIGATION_HISTORY_KEY, JSON.stringify([episode()])], [INVESTIGATION_TRAINING_LAUNCHES_KEY, JSON.stringify([launch])]])); assert.deepEqual(readInvestigationTrainingLaunches(), [launch]); env.cleanup(); });
