import assert from "node:assert/strict";
import test from "node:test";
import { parseGgHand } from "../lib/ggHandParser";
import { buildHeroDecisionView, extractHeroDecisionAnchors, formatAction, toggleReasoningFactor } from "../lib/realHandReasoning";
import { deleteReasoningSnapshotForHand, isRealHandReasoningSnapshot, readReasoningSnapshots, REASONING_SNAPSHOTS_KEY, saveReasoningSnapshot } from "../lib/reasoningSnapshotStorage";
import { clearPrototypeProgress } from "../lib/storage";
import type { RealHandReasoningSnapshot } from "../lib/types";

const hand = (body: string) => parseGgHand(`Poker Hand #A: Hold'em No Limit ($0.01/$0.02) - 2026/08/20 23:19:07\nTable 'T' 6-max Seat #1 is the button\nSeat 5: Hero ($2.00 in chips)\n*** HOLE CARDS ***\nDealt to Hero [Ah Qc]\n${body}\n*** SUMMARY ***`)!;
function installStorage(values = new Map<string,string>()) { Object.defineProperty(globalThis,"window",{ configurable:true,value:{localStorage:{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)}}}); return values; }
function cleanup(){ delete (globalThis as {window?:unknown}).window; }

test("zero ação do Hero produz zero anchors e posts/shows/cashout são ignorados", () => assert.deepEqual(extractHeroDecisionAnchors(hand("Hero: posts big blind $0.02\nHero: shows [Ah Qc]\nHero: Chooses to EV Cashout\nVillain: checks")), []));
for (const [phrase,type] of [["folds","fold"],["checks","check"],["calls $0.18","call"],["bets $0.42","bet"],["raises $0.20 to $1.20","raise"]] as const) test(`Hero ${type} produz anchor`,()=>assert.equal(extractHeroDecisionAnchors(hand(`Hero: ${phrase}`))[0].action,type));
test("duas ações na mesma street têm sequenceIndex e ids distintos",()=>{ const anchors=extractHeroDecisionAnchors(hand("Hero: checks\nVillain: bets $0.10\nHero: calls $0.10")); assert.deepEqual(anchors.map(x=>[x.street,x.sequenceIndex]),[["preflop",0],["preflop",2]]); assert.notEqual(anchors[0].id,anchors[1].id); });
test("view corta ações posteriores e board futuro em cada street",()=>{ const parsed=hand("Hero: calls $0.02\n*** FLOP *** [2c 3d 5s]\nHero: checks\nVillain: bets $0.08\nHero: calls $0.08\n*** TURN *** [2c 3d 5s] [Kd]\nHero: checks\nVillain: bets $0.20\nHero: calls $0.20\n*** RIVER *** [2c 3d 5s Kd] [Qc]\nVillain: checks\nHero: bets $0.40\nVillain: calls $0.40"); const anchors=extractHeroDecisionAnchors(parsed); const pre=buildHeroDecisionView(parsed,anchors[0])!; assert.deepEqual(pre.board,{}); assert.equal(pre.actionsThroughDecision.length,1); const flop=buildHeroDecisionView(parsed,anchors[2])!; assert.deepEqual(flop.board,{flop:["2c","3d","5s"]}); assert.equal(flop.actionsThroughDecision.at(-1)?.actor,"Hero"); assert.equal(flop.actionsThroughDecision.some(x=>x.street==="turn"),false); const turn=buildHeroDecisionView(parsed,anchors[4])!; assert.equal(turn.board.river,undefined); const river=buildHeroDecisionView(parsed,anchors.at(-1)!)!; assert.equal(river.board.river,"Qc"); assert.equal(river.actionsThroughDecision.at(-1)?.actor,"Hero"); });
test("anchor alterada não é reconstruída por aproximação",()=>{ const parsed=hand("Hero: checks"); assert.equal(buildHeroDecisionView(parsed,{...extractHeroDecisionAnchors(parsed)[0],action:"call"}),null); });
test("toggle limita dois, desmarca e torna automatic exclusivo nos dois sentidos",()=>{ assert.deepEqual(toggleReasoningFactor([],"size"),["size"]); assert.deepEqual(toggleReasoningFactor(["size"],"size"),[]); assert.deepEqual(toggleReasoningFactor(["size","board"],"other"),["size","board"]); assert.deepEqual(toggleReasoningFactor(["size","board"],"automatic"),["automatic"]); assert.deepEqual(toggleReasoningFactor(["automatic"],"player-read"),["player-read"]); assert.deepEqual(toggleReasoningFactor(["automatic"],"automatic"),[]); });
test("labels monetários preferem toAmount no raise",()=>{ assert.equal(formatAction({action:"call",amount:.18}),"Call $0,18"); assert.equal(formatAction({action:"raise",amount:.2,toAmount:1.2}),"Raise para $1,20"); assert.equal(formatAction({action:"bet"}),"Bet"); });
const snapshot: RealHandReasoningSnapshot={id:"s",handReviewId:"h",createdAt:"2026-08-21T00:00:00Z",sourceDecision:{street:"river",sequenceIndex:2,action:"call",amount:.2},factors:["size"],selfRatedSupport:"medium"};
test("validação rejeita corrupção, duplicatas, excesso e automatic com suporte",()=>{ assert.equal(isRealHandReasoningSnapshot(snapshot),true); for(const invalid of [{...snapshot,id:""},{...snapshot,createdAt:"no"},{...snapshot,sourceDecision:{...snapshot.sourceDecision,sequenceIndex:-1}},{...snapshot,factors:["size","size"]},{...snapshot,factors:["size","board","other"]},{...snapshot,factors:["automatic","size"]},{...snapshot,factors:["automatic"],selfRatedSupport:"low"}]) assert.equal(isRealHandReasoningSnapshot(invalid),false); });
test("storage é defensivo, único por mão e edição preserva identidade temporal",()=>{ const values=installStorage(new Map([[REASONING_SNAPSHOTS_KEY,"{"]])); assert.deepEqual(readReasoningSnapshots(),[]); saveReasoningSnapshot(snapshot); const edited=saveReasoningSnapshot({...snapshot,id:"new",createdAt:"2027-01-01T00:00:00Z",thought:"texto"}); assert.equal(readReasoningSnapshots().length,1); assert.equal(edited.id,"s"); assert.equal(edited.createdAt,snapshot.createdAt); cleanup(); });
test("exclusão relacionada remove somente o snapshot da mão",()=>{ installStorage(); saveReasoningSnapshot(snapshot); saveReasoningSnapshot({...snapshot,id:"s2",handReviewId:"h2"}); deleteReasoningSnapshotForHand("h"); assert.deepEqual(readReasoningSnapshots().map(x=>x.handReviewId),["h2"]); cleanup(); });
test("reset pedagógico não apaga snapshots",()=>{ const values=installStorage(new Map([[REASONING_SNAPSHOTS_KEY,JSON.stringify([snapshot])],["poker-loop-v1:attempts","[]"]])); clearPrototypeProgress(); assert.ok(values.has(REASONING_SNAPSHOTS_KEY)); cleanup(); });
