import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { archiveRealHandInvestigation, createRealHandInvestigationEpisode, isStoredRealHandInvestigationEpisode, parseRealHandInvestigationHistory, readRealHandInvestigationHistory, REAL_HAND_INVESTIGATION_HISTORY_KEY, summarizeRealHandInvestigationEpisode } from "../lib/realHandInvestigationHistory";
import { REAL_HAND_INVESTIGATION_KEY, type ActiveRealHandInvestigation, type ProspectiveObservedReview } from "../lib/prospectiveRealHandInvestigation";
import { clearPrototypeProgress } from "../lib/storage";

const reviews = (count: number): ProspectiveObservedReview[] => Array.from({ length: count }, (_, index) => ({ snapshotId: `future-${index}`, handReviewId: `future-hand-${index}`, createdAt: `2026-08-22T00:0${index + 2}:00Z`, factorPresent: index < 2, ...(index < 2 ? { selfRatedSupport: index ? "high" as const : "low" as const } : {}) }));
function active(id = "investigation-1", count = 5): ActiveRealHandInvestigation { return { version: 1, id, factor: "size", startedAt: "2026-08-22T00:01:00Z", baselineSnapshotIds: ["a", "b", "c"], baselineHandReviewIds: ["ha", "hb", "hc"], baselineReviewCount: 3, baselineLowOrUnclearCount: 2, prospectiveReviews: reviews(count) }; }
function storage(values = new Map<string, string>()) { Object.defineProperty(globalThis, "window", { configurable: true, value: { localStorage: { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) } } }); return values; }
function cleanup() { delete (globalThis as { window?: unknown }).window; }

test("histórico ausente é vazio", () => assert.deepEqual(parseRealHandInvestigationHistory(null), []));
test("janela 5/5 cria episódio completed com endedAt", () => { const episode = createRealHandInvestigationEpisode(active(), "completed", "2026-08-22T01:00:00Z"); assert.equal(episode.completion, "completed"); assert.equal(episode.endedAt, "2026-08-22T01:00:00Z"); });
test("episódio preserva baseline e observações exatas por cópia profunda", () => { const source = active(); const episode = createRealHandInvestigationEpisode(source, "completed"); source.baselineSnapshotIds[0] = "edited"; source.prospectiveReviews[0].factorPresent = false; assert.deepEqual(episode.baselineSnapshotIds, ["a", "b", "c"]); assert.equal(episode.prospectiveReviews[0].factorPresent, true); });
test("resumo independe de snapshots atuais editados ou apagados", () => { const episode = createRealHandInvestigationEpisode(active(), "completed"); assert.match(summarizeRealHandInvestigationEpisode(episode).text, /2 das 5/); assert.match(summarizeRealHandInvestigationEpisode(episode).text, /1 dessas/); });
test("sexta mão não altera episódio congelado", () => { const episode = createRealHandInvestigationEpisode(active(), "completed"); reviews(6)[5].factorPresent = true; assert.equal(episode.prospectiveReviews.length, 5); });
test("stopped arquiva 1–4 sem conclusão de janela completa", () => { for (const count of [1, 2, 3, 4]) { const episode = createRealHandInvestigationEpisode(active(`i-${count}`, count), "stopped"); const summary = summarizeRealHandInvestigationEpisode(episode); assert.equal(summary.reviewedCount, count); assert.match(summary.text, new RegExp(`${count} das 5 revisões previstas`)); assert.doesNotMatch(summary.text, /5 novas revisões/); } });
test("inconclusive pode ser arquivado com descrição factual", () => assert.match(summarizeRealHandInvestigationEpisode(createRealHandInvestigationEpisode(active("x", 2), "inconclusive")).text, /evidência de origem/));
test("mão apagada não reduz contagem nem é substituída", () => { const episode = createRealHandInvestigationEpisode(active(), "completed"); const currentHands = [{ id: "future-hand-0" }, { id: "another" }]; assert.equal(summarizeRealHandInvestigationEpisode(episode).reviewedCount, 5); assert.deepEqual(episode.prospectiveReviews.filter((review) => currentHands.some(({ id }) => id === review.handReviewId)).map(({ handReviewId }) => handReviewId), ["future-hand-0"]); });
test("mesmo id não duplica e ids diferentes coexistem", () => { const values = storage(); values.set(REAL_HAND_INVESTIGATION_KEY, JSON.stringify(active())); archiveRealHandInvestigation(active(), "completed", "2026-08-22T01:00:00Z"); archiveRealHandInvestigation(active(), "completed", "2026-08-22T01:00:00Z"); archiveRealHandInvestigation(active("investigation-2"), "completed", "2026-08-22T02:00:00Z"); assert.deepEqual(readRealHandInvestigationHistory().map(({ id }) => id), ["investigation-2", "investigation-1"]); cleanup(); });
test("ordena endedAt desc e desempata por id", () => { const a = createRealHandInvestigationEpisode(active("b"), "completed", "2026-08-22T01:00:00Z"); const b = createRealHandInvestigationEpisode(active("a"), "completed", "2026-08-22T01:00:00Z"); const c = createRealHandInvestigationEpisode(active("new"), "completed", "2026-08-22T02:00:00Z"); assert.deepEqual(parseRealHandInvestigationHistory(JSON.stringify([a, c, b])).map(({ id }) => id), ["new", "a", "b"]); });
test("JSON inválido é seguro e item inválido não elimina válido", () => { assert.deepEqual(parseRealHandInvestigationHistory("{"), []); const valid = createRealHandInvestigationEpisode(active(), "completed"); assert.deepEqual(parseRealHandInvestigationHistory(JSON.stringify([{ version: 2 }, valid])), [valid]); });
test("versão, timestamp, fator, review e completion inválidos são ignorados", () => { const valid = createRealHandInvestigationEpisode(active(), "completed"); for (const change of [{ version: 2 }, { endedAt: "never" }, { factor: "skill" }, { prospectiveReviews: [{ nope: true }] }, { completion: "confirmed" }]) assert.deepEqual(parseRealHandInvestigationHistory(JSON.stringify([{ ...valid, ...change }])), []); });
test("completed exige cinco observações", () => assert.throws(() => createRealHandInvestigationEpisode(active("x", 4), "completed")));
test("arquivar limpa somente a investigação ativa correspondente", () => { const values = storage(new Map([[REAL_HAND_INVESTIGATION_KEY, JSON.stringify(active())], ["snapshots", "keep"], ["hands", "keep"]])); archiveRealHandInvestigation(active(), "completed"); assert.equal(values.has(REAL_HAND_INVESTIGATION_KEY), false); assert.equal(values.get("snapshots"), "keep"); assert.equal(values.get("hands"), "keep"); cleanup(); });
test("arquivar não limpa outra investigação ativa", () => { const values = storage(new Map([[REAL_HAND_INVESTIGATION_KEY, JSON.stringify(active("other"))]])); archiveRealHandInvestigation(active(), "completed"); assert.ok(values.has(REAL_HAND_INVESTIGATION_KEY)); cleanup(); });
test("reset pedagógico preserva histórico", () => { const values = storage(new Map([[REAL_HAND_INVESTIGATION_HISTORY_KEY, "history"], ["poker-loop-v1:attempts", "[]"]])); clearPrototypeProgress(); assert.equal(values.get(REAL_HAND_INVESTIGATION_HISTORY_KEY), "history"); cleanup(); });
test("schema validado aceita episódio correto", () => assert.equal(isStoredRealHandInvestigationEpisode(createRealHandInvestigationEpisode(active(), "completed")), true));
test("módulo não depende do motor pedagógico nem mapeia fator para Skill", () => { const source = readFileSync("lib/realHandInvestigationHistory.ts", "utf8"); assert.doesNotMatch(source, /trainingEngine|diagnostics|learningLoop|Attempt|SkillState|ReasoningFactor\s*.*Skill/); });
test("copy histórica evita diagnóstico, comparação e conclusão proibidos", () => { const texts = (["completed", "stopped", "inconclusive"] as const).map((completion) => summarizeRealHandInvestigationEpisode(createRealHandInvestigationEpisode(active(completion, completion === "completed" ? 5 : 2), completion)).text).join(" ").toLowerCase(); assert.doesNotMatch(texts, /leak|erro confirmado|você melhorou|você piorou|hipótese confirmada|hipótese refutada|tendência/); });
test("storage usa chave separada da investigação ativa", () => assert.notEqual(REAL_HAND_INVESTIGATION_HISTORY_KEY, REAL_HAND_INVESTIGATION_KEY));
