import assert from "node:assert/strict";
import test from "node:test";
import { parseGgHand } from "../lib/ggHandParser";
import { buildHandVisualModel, buildHeroDecisionView, extractHeroDecisionAnchors, formatAction, initialQuickReviewAnchor, matchSnapshotDecisionAnchor, quickReviewVisualDecision, toggleReasoningFactor } from "../lib/realHandReasoning";
import { readFileSync } from "node:fs";
import { deleteReasoningSnapshotForHand, isRealHandReasoningSnapshot, readReasoningSnapshots, REASONING_SNAPSHOTS_KEY, saveReasoningSnapshot } from "../lib/reasoningSnapshotStorage";
import { clearPrototypeProgress } from "../lib/storage";
import type { RealHandReasoningSnapshot } from "../lib/types";

const hand = (body: string) => parseGgHand(`Poker Hand #A: Hold'em No Limit ($0.01/$0.02) - 2026/08/20 23:19:07\nTable 'T' 6-max Seat #1 is the button\nSeat 5: Hero ($2.00 in chips)\n*** HOLE CARDS ***\nDealt to Hero [Ah Qc]\n${body}\n*** SUMMARY ***`)!;
function installStorage(values = new Map<string,string>()) { Object.defineProperty(globalThis,"window",{ configurable:true,value:{localStorage:{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)}}}); return values; }
function cleanup(){ delete (globalThis as {window?:unknown}).window; }

test("zero ação do Hero produz zero anchors e posts/shows/cashout são ignorados", () => assert.deepEqual(extractHeroDecisionAnchors(hand("Hero: posts big blind $0.02\nHero: shows [Ah Qc]\nHero: Chooses to EV Cashout\nVillain: checks")), []));
for (const [phrase,type] of [["folds","fold"],["checks","check"],["calls $0.18","call"],["bets $0.42","bet"],["raises $0.20 to $1.20","raise"]] as const) test(`Hero ${type} produz anchor`,()=>assert.equal(extractHeroDecisionAnchors(hand(`Hero: ${phrase}`))[0].action,type));
test("duas ações na mesma street têm sequenceIndex e ids distintos",()=>{ const anchors=extractHeroDecisionAnchors(hand("Hero: checks\nVillain: bets $0.10\nHero: calls $0.10")); assert.deepEqual(anchors.map(x=>[x.street,x.sequenceIndex]),[["preflop",0],["preflop",2]]); assert.notEqual(anchors[0].id,anchors[1].id); });
test("view corta ações posteriores e board futuro em cada street",()=>{ const parsed=hand("Hero: calls $0.02\n*** FLOP *** [2c 3d 5s]\nHero: checks\nVillain: bets $0.08\nHero: calls $0.08\n*** TURN *** [2c 3d 5s] [Kd]\nHero: checks\nVillain: bets $0.20\nHero: calls $0.20\n*** RIVER *** [2c 3d 5s Kd] [Qc]\nVillain: checks\nHero: bets $0.40\nVillain: calls $0.40"); const anchors=extractHeroDecisionAnchors(parsed); const pre=buildHeroDecisionView(parsed,anchors[0])!; assert.deepEqual(pre.board,{}); assert.equal(pre.actionsThroughDecision.length,1); const flop=buildHeroDecisionView(parsed,anchors[2])!; assert.deepEqual(flop.board,{flop:["2c","3d","5s"]}); assert.equal(flop.actionsThroughDecision.at(-1)?.actor,"Hero"); assert.equal(flop.actionsThroughDecision.some(x=>x.street==="turn"),false); const turn=buildHeroDecisionView(parsed,anchors[4])!; assert.equal(turn.board.river,undefined); const river=buildHeroDecisionView(parsed,anchors.at(-1)!)!; assert.equal(river.board.river,"Qc"); assert.equal(river.actionsThroughDecision.at(-1)?.actor,"Hero"); });
test("anchor alterada não é reconstruída por aproximação",()=>{ const parsed=hand("Hero: checks"); assert.equal(buildHeroDecisionView(parsed,{...extractHeroDecisionAnchors(parsed)[0],action:"call"}),null); });
test("edição não escolhe fallback quando a decisão original desaparece",()=>{ const oldHand=hand("Villain: bets $0.20\nHero: calls $0.20"); const oldAnchor=extractHeroDecisionAnchors(oldHand)[0]; const original:RealHandReasoningSnapshot={id:"original",handReviewId:"hand",createdAt:"2026-08-21T00:00:00Z",sourceHandId:oldHand.sourceHandId,sourceDecision:{street:oldAnchor.street,sequenceIndex:oldAnchor.sequenceIndex,action:oldAnchor.action,amount:oldAnchor.amount,allIn:oldAnchor.allIn},thought:"Relato preservado",factors:["size"],selfRatedSupport:"medium"}; installStorage(); saveReasoningSnapshot(original); const current=hand("Hero: checks\nHero: bets $0.40"); const currentAnchors=extractHeroDecisionAnchors(current); assert.equal(matchSnapshotDecisionAnchor(current,original),undefined); assert.equal(initialQuickReviewAnchor(current,original,true),undefined); assert.deepEqual(initialQuickReviewAnchor(current,undefined,false),currentAnchors.at(-1)); assert.deepEqual(readReasoningSnapshots(),[original]); const chosen=currentAnchors[0]; const updated=saveReasoningSnapshot({...original,sourceHandId:current.sourceHandId,sourceDecision:{street:chosen.street,sequenceIndex:chosen.sequenceIndex,action:chosen.action,amount:chosen.amount,toAmount:chosen.toAmount,allIn:chosen.allIn}}); assert.equal(updated.id,original.id); assert.equal(updated.createdAt,original.createdAt); assert.equal(updated.handReviewId,original.handReviewId); assert.equal(updated.thought,original.thought); assert.equal(updated.sourceDecision.action,"check"); cleanup(); });
test("toggle limita dois, desmarca e torna automatic exclusivo nos dois sentidos",()=>{ assert.deepEqual(toggleReasoningFactor([],"size"),["size"]); assert.deepEqual(toggleReasoningFactor(["size"],"size"),[]); assert.deepEqual(toggleReasoningFactor(["size","board"],"other"),["size","board"]); assert.deepEqual(toggleReasoningFactor(["size","board"],"automatic"),["automatic"]); assert.deepEqual(toggleReasoningFactor(["automatic"],"player-read"),["player-read"]); assert.deepEqual(toggleReasoningFactor(["automatic"],"automatic"),[]); });
test("labels monetários preferem toAmount no raise",()=>{ assert.equal(formatAction({action:"call",amount:.18}),"Call $0,18"); assert.equal(formatAction({action:"raise",amount:.2,toAmount:1.2}),"Raise para $1,20"); assert.equal(formatAction({action:"bet"}),"Bet"); });
const snapshot: RealHandReasoningSnapshot={id:"s",handReviewId:"h",createdAt:"2026-08-21T00:00:00Z",sourceHandId:"A",sourceDecision:{street:"river",sequenceIndex:2,action:"call",amount:.2},factors:["size"],selfRatedSupport:"medium"};
test("validação rejeita corrupção, duplicatas, excesso e automatic com suporte",()=>{ assert.equal(isRealHandReasoningSnapshot(snapshot),true); for(const invalid of [{...snapshot,id:""},{...snapshot,createdAt:"no"},{...snapshot,sourceDecision:{...snapshot.sourceDecision,sequenceIndex:-1}},{...snapshot,factors:["size","size"]},{...snapshot,factors:["size","board","other"]},{...snapshot,factors:["automatic","size"]},{...snapshot,factors:["automatic"],selfRatedSupport:"low"}]) assert.equal(isRealHandReasoningSnapshot(invalid),false); });
test("storage é defensivo, único por mão e edição preserva identidade temporal",()=>{ const values=installStorage(new Map([[REASONING_SNAPSHOTS_KEY,"{"]])); assert.deepEqual(readReasoningSnapshots(),[]); saveReasoningSnapshot(snapshot); const edited=saveReasoningSnapshot({...snapshot,id:"new",createdAt:"2027-01-01T00:00:00Z",thought:"texto"}); assert.equal(readReasoningSnapshots().length,1); assert.equal(edited.id,"s"); assert.equal(edited.createdAt,snapshot.createdAt); cleanup(); });
test("exclusão relacionada remove somente o snapshot da mão",()=>{ installStorage(); saveReasoningSnapshot(snapshot); saveReasoningSnapshot({...snapshot,id:"s2",handReviewId:"h2"}); deleteReasoningSnapshotForHand("h"); assert.deepEqual(readReasoningSnapshots().map(x=>x.handReviewId),["h2"]); cleanup(); });
test("reset pedagógico não apaga snapshots",()=>{ const values=installStorage(new Map([[REASONING_SNAPSHOTS_KEY,JSON.stringify([snapshot])],["poker-loop-v1:attempts","[]"]])); clearPrototypeProgress(); assert.ok(values.has(REASONING_SNAPSHOTS_KEY)); cleanup(); });

test("anchor e snapshot novo preservam all-in",()=>{ const parsed=hand("Hero: calls $1.20 and is all-in"); const anchor=extractHeroDecisionAnchors(parsed)[0]; assert.equal(anchor.allIn,true); installStorage(); const saved=saveReasoningSnapshot({id:"all",handReviewId:"all-hand",createdAt:"2026-08-21T00:00:00Z",sourceHandId:parsed.sourceHandId,sourceDecision:{street:anchor.street,sequenceIndex:anchor.sequenceIndex,action:anchor.action,amount:anchor.amount,toAmount:anchor.toAmount,allIn:anchor.allIn},factors:[]}); assert.equal(saved.sourceDecision.allIn,true); assert.equal(readReasoningSnapshots()[0].sourceDecision.allIn,true); cleanup(); });
test("labels mostram bet, call e raise all-in",()=>{ assert.equal(formatAction({type:"bet",amount:2,allIn:true}),"Bet $2,00 · all-in"); assert.equal(formatAction({type:"call",amount:1.2,allIn:true}),"Call $1,20 · all-in"); assert.equal(formatAction({type:"raise",amount:.6,toAmount:1.6,allIn:true}),"Raise para $1,60 · all-in"); });
test("matching exige proveniência e todos os dados observáveis exatos",()=>{ const parsed=hand("Villain: bets $0.40\nHero: raises $1.20 to $1.60 and is all-in"); const anchor=extractHeroDecisionAnchors(parsed)[0]; const exact:RealHandReasoningSnapshot={id:"exact",handReviewId:"h",createdAt:"2026-08-21T00:00:00Z",sourceHandId:parsed.sourceHandId,sourceDecision:{street:anchor.street,sequenceIndex:anchor.sequenceIndex,action:anchor.action,amount:anchor.amount,toAmount:anchor.toAmount,allIn:anchor.allIn},factors:[]}; assert.deepEqual(matchSnapshotDecisionAnchor(parsed,exact),anchor); assert.equal(matchSnapshotDecisionAnchor({...parsed,sourceHandId:"B"},exact),undefined); assert.equal(matchSnapshotDecisionAnchor(parsed,{...exact,sourceDecision:{...exact.sourceDecision,amount:9}}),undefined); assert.equal(matchSnapshotDecisionAnchor(parsed,{...exact,sourceDecision:{...exact.sourceDecision,toAmount:9}}),undefined); assert.equal(matchSnapshotDecisionAnchor(parsed,{...exact,sourceDecision:{...exact.sourceDecision,allIn:false}}),undefined); });
test("snapshot legado é lido mas não confirmado nem salvo como novo",()=>{ const {sourceHandId:_sourceHandId,...legacy}=snapshot; installStorage(new Map([[REASONING_SNAPSHOTS_KEY,JSON.stringify([legacy])]])); assert.deepEqual(readReasoningSnapshots(),[legacy]); assert.equal(matchSnapshotDecisionAnchor(hand("Hero: checks"),legacy),undefined); assert.throws(()=>saveReasoningSnapshot(legacy as RealHandReasoningSnapshot)); cleanup(); });
test("sourceHandId presente vazio ou inválido é rejeitado",()=>{ assert.equal(isRealHandReasoningSnapshot({...snapshot,sourceHandId:""}),false); assert.equal(isRealHandReasoningSnapshot({...snapshot,sourceHandId:42}),false); });
test("allIn armazenado precisa ser boolean",()=>{ assert.equal(isRealHandReasoningSnapshot({...snapshot,sourceDecision:{...snapshot.sourceDecision,allIn:"yes"}}),false); });
test("Decision View rejeita anchor com amount, toAmount ou allIn adulterado",()=>{ const parsed=hand("Hero: raises $1.20 to $1.60 and is all-in"); const anchor=extractHeroDecisionAnchors(parsed)[0]; assert.equal(buildHeroDecisionView(parsed,{...anchor,amount:9}),null); assert.equal(buildHeroDecisionView(parsed,{...anchor,toAmount:9}),null); assert.equal(buildHeroDecisionView(parsed,{...anchor,allIn:false}),null); assert.ok(buildHeroDecisionView(parsed,anchor)); });

test("modelo visual organiza board e ações por street sem carregar texto bruto",()=>{ const parsed=hand("Hero: calls $0.02\n*** FLOP *** [2c 3d 5s]\nVillain: checks\nHero: bets $0.08\n*** TURN *** [2c 3d 5s] [Kd]\nHero: checks"); const visual=buildHandVisualModel(parsed)!; assert.deepEqual(visual.map(x=>x.street),["preflop","flop","turn"]); assert.deepEqual(visual[1].board,["2c","3d","5s"]); assert.deepEqual(visual[1].actions.map(x=>x.actor),["Villain","Hero"]); assert.equal("rawHandText" in visual,false); });
test("modelo visual da decisão destaca a ação e mantém corte anti-hindsight",()=>{ const parsed=hand("Hero: calls $0.02\n*** FLOP *** [2c 3d 5s]\nVillain: checks\nHero: bets $0.08\n*** TURN *** [2c 3d 5s] [Kd]\nVillain: bets $0.20\nHero: calls $0.20"); const anchor=extractHeroDecisionAnchors(parsed)[1]; const visual=buildHandVisualModel(parsed,anchor)!; assert.deepEqual(visual.map(x=>x.street),["preflop","flop"]); assert.equal(visual.flatMap(x=>x.actions).at(-1)?.selected,true); assert.equal(visual.flatMap(x=>x.actions).some(x=>x.street==="turn"),false); });

const fourStreetHand=()=>hand("Hero: calls $0.02\n*** FLOP *** [2c 3d 5s]\nVillain: checks\nHero: bets $0.08\nVillain: calls $0.08\n*** TURN *** [2c 3d 5s] [Kd]\nHero: checks\nVillain: bets $0.20\nHero: calls $0.20\n*** RIVER *** [2c 3d 5s Kd] [Qc]\nHero: checks\nVillain: bets $0.40\nHero: folds");
test("idle escolhe a visualização completa",()=>{ const parsed=fourStreetHand(); const state=quickReviewVisualDecision("idle",extractHeroDecisionAnchors(parsed)[1])!; assert.equal(state.kind,"full"); assert.deepEqual(buildHandVisualModel(parsed)!.map(x=>x.street),["preflop","flop","turn","river"]); });
test("review no flop contém somente informações até a decisão no flop",()=>{ const parsed=fourStreetHand(); const anchor=extractHeroDecisionAnchors(parsed)[1]; const state=quickReviewVisualDecision("choose",anchor)!; assert.equal(state.kind,"decision"); const visual=buildHandVisualModel(parsed,state.kind==="decision"?state.anchor:undefined)!; assert.deepEqual(visual.map(x=>x.street),["preflop","flop"]); assert.equal(visual.flatMap(x=>x.actions).at(-1)?.selected,true); });
test("review no turn não contém river nem ações posteriores à anchor",()=>{ const parsed=fourStreetHand(); const anchor=extractHeroDecisionAnchors(parsed)[2]; const visual=buildHandVisualModel(parsed,anchor)!; assert.deepEqual(visual.map(x=>x.street),["preflop","flop","turn"]); assert.equal(visual.some(x=>x.street==="river"),false); assert.equal(visual.flatMap(x=>x.actions).at(-1)?.sequenceIndex,anchor.sequenceIndex); });
test("trocar a anchor recalcula o corte sem reter streets futuras",()=>{ const parsed=fourStreetHand(); const anchors=extractHeroDecisionAnchors(parsed); const turn=buildHandVisualModel(parsed,quickReviewVisualDecision("choose",anchors[2])!.kind==="decision"?anchors[2]:undefined)!; const flop=buildHandVisualModel(parsed,quickReviewVisualDecision("choose",anchors[1])!.kind==="decision"?anchors[1]:undefined)!; assert.deepEqual(turn.map(x=>x.street),["preflop","flop","turn"]); assert.deepEqual(flop.map(x=>x.street),["preflop","flop"]); });
test("composição mantém uma superfície visual por sugestão e Decision View própria na mão salva",()=>{ const page=readFileSync("app/hands/page.tsx","utf8"); const card=readFileSync("app/hands/HandSuggestionCard.tsx","utf8"); assert.equal((card.match(/<ParsedHandVisualization rawHandText=/g)??[]).length,1); assert.match(card,/<ParsedHandVisualization rawHandText=\{suggestion\.rawHandText\}/); assert.doesNotMatch(page,/<ParsedHandVisualization/); assert.match(page,/<QuickReview key=/); assert.match(card,/<details className="raw-history"><summary>Ver histórico bruto<\/summary>/); });
