"use client";
import { useMemo, useState } from "react";
import { parseGgHand } from "@/lib/ggHandParser";
import { buildHeroDecisionView, decisionStreetLabels, extractHeroDecisionAnchors, formatAction, initialQuickReviewAnchor, matchSnapshotDecisionAnchor, quickReviewVisualDecision, reasoningFactorLabels, toggleReasoningFactor } from "@/lib/realHandReasoning";
import { readReasoningSnapshots, saveReasoningSnapshot } from "@/lib/reasoningSnapshotStorage";
import type { HeroDecisionAnchor, RealHandReasoningSnapshot, RealHandReview, ReasoningFactor, SelfRatedSupport } from "@/lib/types";
import type { QuickReviewMode } from "@/lib/realHandReasoning";
import { HandVisualization } from "@/app/components/HandVisualization";
const supportLabels: Record<SelfRatedSupport,string>={low:"Baixa",medium:"Média",high:"Alta",unclear:"Não estava claro"};
export function QuickReview({hand,onSnapshotSaved}:{hand:RealHandReview;onSnapshotSaved?:()=>void}) {
 const parsed=useMemo(()=>parseGgHand(hand.rawHandText),[hand.rawHandText]); const anchors=useMemo(()=>parsed?extractHeroDecisionAnchors(parsed):[],[parsed]);
 const [snapshot,setSnapshot]=useState(()=>readReasoningSnapshots().find(x=>x.handReviewId===hand.id)); const [mode,setMode]=useState<QuickReviewMode>("idle");
 const matched=snapshot&&parsed ? matchSnapshotDecisionAnchor(parsed,snapshot) : undefined;
 const [anchor,setAnchor]=useState<HeroDecisionAnchor|undefined>(snapshot?matched:anchors.at(-1)); const [showAll,setShowAll]=useState(false); const [selectedFactors,setFactors]=useState<ReasoningFactor[]>(snapshot?.factors??[]); const [support,setSupport]=useState<SelfRatedSupport|undefined>(snapshot?.selfRatedSupport);
 const [editingExisting,setEditingExisting]=useState(false);
 const view=parsed&&anchor?buildHeroDecisionView(parsed,anchor):null;
 function begin(edit=false){setEditingExisting(edit);setAnchor(parsed ? initialQuickReviewAnchor(parsed,snapshot,edit) : undefined);setFactors(edit?snapshot?.factors??[]:[]);setSupport(edit?snapshot?.selfRatedSupport:undefined);setShowAll(edit);setMode("choose");}
 function save(){if(!anchor||!parsed)return;const next:RealHandReasoningSnapshot={id:snapshot?.id??crypto.randomUUID(),handReviewId:hand.id,createdAt:snapshot?.createdAt??new Date().toISOString(),sourceHandId:parsed.sourceHandId,sourceDecision:{street:anchor.street,sequenceIndex:anchor.sequenceIndex,action:anchor.action,amount:anchor.amount,toAmount:anchor.toAmount,allIn:anchor.allIn},...(snapshot?.thought !== undefined ? { thought: snapshot.thought } : {}),factors:selectedFactors,selfRatedSupport:selectedFactors[0]==="automatic"?undefined:support};setSnapshot(saveReasoningSnapshot(next));onSnapshotSaved?.();setMode("idle");}
 if(!parsed)return <section className="quick-review unavailable">Revisão rápida automática não disponível para este histórico.</section>;
 const visual=quickReviewVisualDecision(mode,anchor); const handVisual=visual&&<HandVisualization hand={parsed} decision={visual.kind==="decision"?visual.anchor:undefined}/>;
 if(mode==="idle"&&snapshot&&!matched)return <section className="quick-review">{handVisual}<div className="eyebrow">REVISÃO RÁPIDA CONCLUÍDA</div><p>A revisão rápida foi registrada anteriormente, mas a decisão original não pôde ser reconstruída a partir do histórico atual.</p><button className="primary-cta compact" onClick={()=>begin(true)}>Escolher decisão</button></section>;
 if(mode==="idle"&&snapshot)return <section className="quick-review">{handVisual}<div className="eyebrow">REVISÃO RÁPIDA CONCLUÍDA</div><h3>{decisionStreetLabels[snapshot.sourceDecision.street]} · {formatAction(snapshot.sourceDecision)}</h3>{snapshot.factors.length>0&&<><strong>O que pesou:</strong><ul>{snapshot.factors.map(x=><li key={x}>{reasoningFactorLabels[x]}</li>)}</ul></>}{snapshot.selfRatedSupport&&<p><strong>Sustentação percebida:</strong> {supportLabels[snapshot.selfRatedSupport]}</p>}<div className="quick-actions"><button className="text-button" onClick={()=>{setAnchor(matched);setMode("view")}}>Ver decisão</button><button className="primary-cta compact" onClick={()=>begin(true)}>Editar revisão rápida</button></div></section>;
 if(mode==="idle")return <section className="quick-review">{handVisual}<div className="eyebrow">REVISÃO RÁPIDA</div><h3>Reconstrua uma das suas decisões sem começar pelo desfecho da mão.</h3><button className="primary-cta compact" onClick={()=>begin()}>Revisar rapidamente</button></section>;
 if(mode==="choose")return <section className="quick-review">{handVisual}<div className="eyebrow">{editingExisting||showAll?"ESCOLHA DA DECISÃO":"COMEÇAR POR AQUI"}</div>{editingExisting&&!matched&&<><p>Esta revisão foi registrada anteriormente, mas a decisão original não pôde ser reconstruída a partir do histórico atual.</p>{anchors.length>0&&<p>Escolha uma decisão do histórico atual se quiser atualizar esta revisão.</p>}</>}{!anchors.length?<><p>Não encontramos uma decisão do Herói que possa ser reconstruída automaticamente nesta mão.</p><button className="text-button" onClick={()=>setMode("idle")}>Voltar</button></>:<><h3>{anchor&&`${decisionStreetLabels[anchor.street]} · ${formatAction(anchor)}`}</h3><p>{editingExisting||showAll?"Escolha a decisão que você quer revisar.":"Começar pela sua última decisão?"}</p>{showAll&&<div className="decision-list">{anchors.map(x=><button type="button" key={x.id} className={x.id===anchor?.id?"selected":""} onClick={()=>setAnchor(x)}>{decisionStreetLabels[x.street]} · {formatAction(x)}</button>)}</div>}<div className="quick-actions"><button className="primary-cta compact" disabled={!anchor} onClick={()=>setMode("form")}>Revisar esta decisão</button>{!showAll&&<button className="text-button" onClick={()=>setShowAll(true)}>Escolher outra</button>}<button className="text-button" onClick={()=>setMode("idle")}>Cancelar</button></div></>}</section>;
 if(mode==="view"&&!view)return <section className="quick-review"><p>Esta revisão foi registrada anteriormente, mas a decisão não pôde ser reconstruída a partir do histórico atual.</p><button className="text-button" onClick={()=>setMode("idle")}>Voltar</button></section>;
 return <section className="quick-review">{view&&handVisual} {mode==="form"&&<div className="reasoning-form"><fieldset><legend>O que mais pesou nessa decisão?</legend><small>Escolha até 2 fatores.</small><div className="factor-grid">{(Object.keys(reasoningFactorLabels) as ReasoningFactor[]).map(x=><button type="button" className={selectedFactors.includes(x)?"selected":""} key={x} aria-pressed={selectedFactors.includes(x)} onClick={()=>{const next=toggleReasoningFactor(selectedFactors,x);setFactors(next);if(next[0]==="automatic")setSupport(undefined)}}>{reasoningFactorLabels[x]}</button>)}</div></fieldset>{selectedFactors[0]!=="automatic"&&<fieldset><legend>Quanta sustentação você sentia que tinha para essa decisão?</legend><div className="factor-grid">{(Object.keys(supportLabels) as SelfRatedSupport[]).map(x=><button type="button" className={support===x?"selected":""} aria-pressed={support===x} key={x} onClick={()=>setSupport(support===x?undefined:x)}>{supportLabels[x]}</button>)}</div></fieldset>}<div className="quick-actions"><button className="primary-cta compact" disabled={!selectedFactors.length || (selectedFactors[0]!=="automatic"&&!support)} onClick={save}>Salvar revisão rápida</button><button className="text-button" onClick={()=>setMode("idle")}>Cancelar</button></div></div>}{mode==="view"&&<button className="text-button" onClick={()=>setMode("idle")}>Voltar</button>}</section>;
}
