"use client";
import { useMemo, useState } from "react";
import { parseGgHand } from "@/lib/ggHandParser";
import { buildHeroDecisionView, decisionStreetLabels, extractHeroDecisionAnchors, formatAction, initialQuickReviewAnchor, matchSnapshotDecisionAnchor, reasoningFactorLabels, toggleReasoningFactor } from "@/lib/realHandReasoning";
import { readReasoningSnapshots, saveReasoningSnapshot } from "@/lib/reasoningSnapshotStorage";
import type { HeroDecisionAnchor, RealHandReasoningSnapshot, RealHandReview, ReasoningFactor, SelfRatedSupport } from "@/lib/types";
const supportLabels: Record<SelfRatedSupport,string>={low:"Pouca",medium:"Alguma",high:"Bastante",unclear:"Não estava claro"};
const cardLabel=(card:string)=>card.replace("h","♥").replace("d","♦").replace("c","♣").replace("s","♠");
export function QuickReview({hand}:{hand:RealHandReview}) {
 const parsed=useMemo(()=>parseGgHand(hand.rawHandText),[hand.rawHandText]); const anchors=useMemo(()=>parsed?extractHeroDecisionAnchors(parsed):[],[parsed]);
 const [snapshot,setSnapshot]=useState(()=>readReasoningSnapshots().find(x=>x.handReviewId===hand.id)); const [mode,setMode]=useState<"idle"|"choose"|"form"|"view">("idle");
 const matched=snapshot&&parsed ? matchSnapshotDecisionAnchor(parsed,snapshot) : undefined;
 const [anchor,setAnchor]=useState<HeroDecisionAnchor|undefined>(snapshot?matched:anchors.at(-1)); const [showAll,setShowAll]=useState(false); const [thought,setThought]=useState(snapshot?.thought??""); const [selectedFactors,setFactors]=useState<ReasoningFactor[]>(snapshot?.factors??[]); const [support,setSupport]=useState<SelfRatedSupport|undefined>(snapshot?.selfRatedSupport);
 const [editingExisting,setEditingExisting]=useState(false);
 const view=parsed&&anchor?buildHeroDecisionView(parsed,anchor):null;
 function begin(edit=false){setEditingExisting(edit);setAnchor(parsed ? initialQuickReviewAnchor(parsed,snapshot,edit) : undefined);setThought(edit?snapshot?.thought??"":"");setFactors(edit?snapshot?.factors??[]:[]);setSupport(edit?snapshot?.selfRatedSupport:undefined);setShowAll(edit);setMode("choose");}
 function save(){if(!anchor||!parsed)return;const next:RealHandReasoningSnapshot={id:snapshot?.id??crypto.randomUUID(),handReviewId:hand.id,createdAt:snapshot?.createdAt??new Date().toISOString(),sourceHandId:parsed.sourceHandId,sourceDecision:{street:anchor.street,sequenceIndex:anchor.sequenceIndex,action:anchor.action,amount:anchor.amount,toAmount:anchor.toAmount,allIn:anchor.allIn},thought:thought.trim()||undefined,factors:selectedFactors,selfRatedSupport:selectedFactors[0]==="automatic"?undefined:support};setSnapshot(saveReasoningSnapshot(next));setMode("idle");}
 if(!parsed)return <section className="quick-review unavailable">Revisão rápida automática não disponível para este histórico.</section>;
 if(mode==="idle"&&snapshot&&!matched)return <section className="quick-review"><div className="eyebrow">REVISÃO RÁPIDA CONCLUÍDA</div><p>A revisão rápida foi registrada anteriormente, mas a decisão original não pôde ser reconstruída a partir do histórico atual.</p>{snapshot.thought&&<p><strong>O que você registrou:</strong><br/>{snapshot.thought}</p>}<button className="primary-cta compact" onClick={()=>begin(true)}>Escolher decisão</button></section>;
 if(mode==="idle"&&snapshot)return <section className="quick-review"><div className="eyebrow">REVISÃO RÁPIDA CONCLUÍDA</div><h3>{decisionStreetLabels[snapshot.sourceDecision.street]} · {formatAction(snapshot.sourceDecision)}</h3>{snapshot.factors.length>0&&<><strong>O que pesou:</strong><ul>{snapshot.factors.map(x=><li key={x}>{reasoningFactorLabels[x]}</li>)}</ul></>}{snapshot.selfRatedSupport&&<p><strong>Sustentação percebida:</strong> {supportLabels[snapshot.selfRatedSupport]}</p>}{snapshot.thought&&<p><strong>O que você registrou:</strong><br/>{snapshot.thought}</p>}<div className="quick-actions"><button className="text-button" onClick={()=>{setAnchor(matched);setMode("view")}}>Ver decisão</button><button className="primary-cta compact" onClick={()=>begin(true)}>Editar revisão rápida</button></div></section>;
 if(mode==="idle")return <section className="quick-review"><div className="eyebrow">REVISÃO RÁPIDA</div><h3>Reconstrua uma das suas decisões sem começar pelo desfecho da mão.</h3><button className="primary-cta compact" onClick={()=>begin()}>Revisar rapidamente</button></section>;
 if(mode==="choose")return <section className="quick-review"><div className="eyebrow">{editingExisting||showAll?"ESCOLHA DA DECISÃO":"COMEÇAR POR AQUI"}</div>{editingExisting&&!matched&&<><p>Esta revisão foi registrada anteriormente, mas a decisão original não pôde ser reconstruída a partir do histórico atual.</p>{anchors.length>0&&<p>Escolha uma decisão do histórico atual se quiser atualizar esta revisão.</p>}</>}{!anchors.length?<><p>Não encontramos uma decisão do Herói que possa ser reconstruída automaticamente nesta mão.</p><button className="text-button" onClick={()=>setMode("idle")}>Voltar</button></>:<><h3>{anchor&&`${decisionStreetLabels[anchor.street]} · ${formatAction(anchor)}`}</h3><p>{editingExisting||showAll?"Escolha a decisão que você quer revisar.":"Começar pela sua última decisão?"}</p>{showAll&&<div className="decision-list">{anchors.map(x=><button type="button" key={x.id} className={x.id===anchor?.id?"selected":""} onClick={()=>setAnchor(x)}>{decisionStreetLabels[x.street]} · {formatAction(x)}</button>)}</div>}<div className="quick-actions"><button className="primary-cta compact" disabled={!anchor} onClick={()=>setMode("form")}>Revisar esta decisão</button>{!showAll&&<button className="text-button" onClick={()=>setShowAll(true)}>Escolher outra</button>}<button className="text-button" onClick={()=>setMode("idle")}>Cancelar</button></div></>}</section>;
 if(mode==="view"&&!view)return <section className="quick-review"><p>Esta revisão foi registrada anteriormente, mas a decisão não pôde ser reconstruída a partir do histórico atual.</p><button className="text-button" onClick={()=>setMode("idle")}>Voltar</button></section>;
 return <section className="quick-review">{view&&<DecisionView view={view}/>} {mode==="form"&&<div className="reasoning-form"><label>O que passou pela sua cabeça nessa decisão?<small>Opcional. Uma frase já basta.</small><textarea rows={3} value={thought} onChange={e=>setThought(e.target.value)}/></label><fieldset><legend>Além das suas cartas, o que mais pesou nessa decisão?</legend><div className="factor-grid">{(Object.keys(reasoningFactorLabels) as ReasoningFactor[]).map(x=><button type="button" className={selectedFactors.includes(x)?"selected":""} key={x} aria-pressed={selectedFactors.includes(x)} onClick={()=>{const next=toggleReasoningFactor(selectedFactors,x);setFactors(next);if(next[0]==="automatic")setSupport(undefined)}}>{reasoningFactorLabels[x]}</button>)}</div></fieldset>{selectedFactors[0]!=="automatic"&&<fieldset><legend>Naquele momento, quanto você achava que tinha de informação para sustentar sua leitura?</legend><div className="factor-grid">{(Object.keys(supportLabels) as SelfRatedSupport[]).map(x=><button type="button" className={support===x?"selected":""} key={x} onClick={()=>setSupport(support===x?undefined:x)}>{supportLabels[x]}</button>)}</div></fieldset>}<div className="quick-actions"><button className="primary-cta compact" onClick={save}>Salvar revisão rápida</button><button className="text-button" onClick={()=>setMode("idle")}>Cancelar</button></div></div>}{mode==="view"&&<button className="text-button" onClick={()=>setMode("idle")}>Voltar</button>}</section>;
}
function DecisionView({view}:{view:NonNullable<ReturnType<typeof buildHeroDecisionView>>}){const board=[...(view.board.flop??[]),...(view.board.turn?[view.board.turn]:[]),...(view.board.river?[view.board.river]:[])];return <div className="decision-view"><div className="hero-cards">{view.heroCards.map(cardLabel).join(" ")}</div>{board.length>0&&<><div className="eyebrow">BOARD</div><div className="visible-board">{board.map(cardLabel).join(" ")}</div></>}<div className="eyebrow">AÇÕES ATÉ AQUI</div>{view.actionsThroughDecision.slice(0,-1).map((x,i)=><p key={i}>{x.actor==="Hero"?"Herói":x.actor} {formatAction(x).toLowerCase()}</p>)}<div className="chosen-action"><strong>SUA DECISÃO</strong><span>Herói {formatAction(view.actionsThroughDecision.at(-1)!).toLowerCase()}</span></div></div>}
